// Code generated by protoc-gen-go. DO NOT EDIT.
// source: rpc.proto

package rpc

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type App struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Namespace            string   `protobuf:"bytes,2,opt,name=namespace,proto3" json:"namespace,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *App) Reset()         { *m = App{} }
func (m *App) String() string { return proto.CompactTextString(m) }
func (*App) ProtoMessage()    {}
func (*App) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{0}
}

func (m *App) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_App.Unmarshal(m, b)
}
func (m *App) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_App.Marshal(b, m, deterministic)
}
func (m *App) XXX_Merge(src proto.Message) {
	xxx_messageInfo_App.Merge(m, src)
}
func (m *App) XXX_Size() int {
	return xxx_messageInfo_App.Size(m)
}
func (m *App) XXX_DiscardUnknown() {
	xxx_messageInfo_App.DiscardUnknown(m)
}

var xxx_messageInfo_App proto.InternalMessageInfo

func (m *App) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *App) GetNamespace() string {
	if m != nil {
		return m.Namespace
	}
	return ""
}

type TerminalSize struct {
	Width                uint32   `protobuf:"varint,1,opt,name=Width,proto3" json:"Width,omitempty"`
	Height               uint32   `protobuf:"varint,2,opt,name=Height,proto3" json:"Height,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TerminalSize) Reset()         { *m = TerminalSize{} }
func (m *TerminalSize) String() string { return proto.CompactTextString(m) }
func (*TerminalSize) ProtoMessage()    {}
func (*TerminalSize) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{1}
}

func (m *TerminalSize) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TerminalSize.Unmarshal(m, b)
}
func (m *TerminalSize) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TerminalSize.Marshal(b, m, deterministic)
}
func (m *TerminalSize) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TerminalSize.Merge(m, src)
}
func (m *TerminalSize) XXX_Size() int {
	return xxx_messageInfo_TerminalSize.Size(m)
}
func (m *TerminalSize) XXX_DiscardUnknown() {
	xxx_messageInfo_TerminalSize.DiscardUnknown(m)
}

var xxx_messageInfo_TerminalSize proto.InternalMessageInfo

func (m *TerminalSize) GetWidth() uint32 {
	if m != nil {
		return m.Width
	}
	return 0
}

func (m *TerminalSize) GetHeight() uint32 {
	if m != nil {
		return m.Height
	}
	return 0
}

type StdIn struct {
	App                  *App          `protobuf:"bytes,1,opt,name=App,proto3" json:"App,omitempty"`
	Input                []string      `protobuf:"bytes,2,rep,name=Input,proto3" json:"Input,omitempty"`
	TerminalSize         *TerminalSize `protobuf:"bytes,3,opt,name=TerminalSize,proto3" json:"TerminalSize,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *StdIn) Reset()         { *m = StdIn{} }
func (m *StdIn) String() string { return proto.CompactTextString(m) }
func (*StdIn) ProtoMessage()    {}
func (*StdIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{2}
}

func (m *StdIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StdIn.Unmarshal(m, b)
}
func (m *StdIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StdIn.Marshal(b, m, deterministic)
}
func (m *StdIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StdIn.Merge(m, src)
}
func (m *StdIn) XXX_Size() int {
	return xxx_messageInfo_StdIn.Size(m)
}
func (m *StdIn) XXX_DiscardUnknown() {
	xxx_messageInfo_StdIn.DiscardUnknown(m)
}

var xxx_messageInfo_StdIn proto.InternalMessageInfo

func (m *StdIn) GetApp() *App {
	if m != nil {
		return m.App
	}
	return nil
}

func (m *StdIn) GetInput() []string {
	if m != nil {
		return m.Input
	}
	return nil
}

func (m *StdIn) GetTerminalSize() *TerminalSize {
	if m != nil {
		return m.TerminalSize
	}
	return nil
}

type StdOut struct {
	Output               string   `protobuf:"bytes,1,opt,name=Output,proto3" json:"Output,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StdOut) Reset()         { *m = StdOut{} }
func (m *StdOut) String() string { return proto.CompactTextString(m) }
func (*StdOut) ProtoMessage()    {}
func (*StdOut) Descriptor() ([]byte, []int) {
	return fileDescriptor_77a6da22d6a3feb1, []int{3}
}

func (m *StdOut) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StdOut.Unmarshal(m, b)
}
func (m *StdOut) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StdOut.Marshal(b, m, deterministic)
}
func (m *StdOut) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StdOut.Merge(m, src)
}
func (m *StdOut) XXX_Size() int {
	return xxx_messageInfo_StdOut.Size(m)
}
func (m *StdOut) XXX_DiscardUnknown() {
	xxx_messageInfo_StdOut.DiscardUnknown(m)
}

var xxx_messageInfo_StdOut proto.InternalMessageInfo

func (m *StdOut) GetOutput() string {
	if m != nil {
		return m.Output
	}
	return ""
}

func init() {
	proto.RegisterType((*App)(nil), "rpc.App")
	proto.RegisterType((*TerminalSize)(nil), "rpc.TerminalSize")
	proto.RegisterType((*StdIn)(nil), "rpc.StdIn")
	proto.RegisterType((*StdOut)(nil), "rpc.StdOut")
}

func init() { proto.RegisterFile("rpc.proto", fileDescriptor_77a6da22d6a3feb1) }

var fileDescriptor_77a6da22d6a3feb1 = []byte{
	// 248 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x54, 0x90, 0x31, 0x4f, 0xc3, 0x30,
	0x10, 0x85, 0x09, 0x21, 0x01, 0x5f, 0xe9, 0xc0, 0xa9, 0x42, 0x51, 0xc5, 0x50, 0x79, 0x8a, 0x18,
	0x2a, 0x54, 0x54, 0xb1, 0xb0, 0x64, 0x82, 0x4e, 0x91, 0x1c, 0x24, 0xe6, 0x90, 0x58, 0x24, 0x52,
	0xea, 0x9e, 0xc2, 0x79, 0xe1, 0xd7, 0x23, 0x5f, 0x8a, 0xa0, 0x93, 0xef, 0xf9, 0xfc, 0xde, 0x7d,
	0x3e, 0x50, 0x23, 0x35, 0x6b, 0x1a, 0x0f, 0x7c, 0xc0, 0x78, 0xa4, 0x46, 0x3f, 0x41, 0x5c, 0x10,
	0x21, 0xc2, 0x85, 0xab, 0xf7, 0x36, 0x8b, 0x56, 0x51, 0xae, 0x8c, 0xd4, 0x78, 0x07, 0x2a, 0x9c,
	0x5f, 0x54, 0x37, 0x36, 0x3b, 0x97, 0xc6, 0xdf, 0x85, 0x7e, 0x86, 0xeb, 0x37, 0x3b, 0xee, 0x7b,
	0x57, 0x0f, 0x55, 0xff, 0x6d, 0x71, 0x01, 0xc9, 0x7b, 0xdf, 0x72, 0x27, 0x11, 0x73, 0x33, 0x09,
	0xbc, 0x85, 0xf4, 0xd5, 0xf6, 0x9f, 0x1d, 0x4b, 0xc0, 0xdc, 0x1c, 0x95, 0x26, 0x48, 0x2a, 0x6e,
	0x77, 0x0e, 0x97, 0x32, 0x5f, 0x4c, 0xb3, 0xcd, 0xd5, 0x3a, 0xd0, 0x15, 0x44, 0x46, 0xa0, 0x16,
	0x90, 0xec, 0x1c, 0xf9, 0xe0, 0x8d, 0x73, 0x65, 0x26, 0x81, 0xdb, 0xd3, 0xc1, 0x59, 0x2c, 0xd6,
	0x1b, 0xb1, 0xfe, 0x6f, 0x98, 0x93, 0x67, 0x7a, 0x05, 0x69, 0xc5, 0x6d, 0xe9, 0x39, 0x30, 0x95,
	0x9e, 0x43, 0xee, 0xf4, 0xdb, 0xa3, 0xda, 0x6c, 0xe1, 0xb2, 0x20, 0x7a, 0xa9, 0xd9, 0xe2, 0x3d,
	0xa8, 0x92, 0xac, 0xab, 0x3a, 0x3b, 0x0c, 0x08, 0x12, 0x2d, 0xb8, 0xcb, 0xd9, 0x6f, 0x5d, 0x7a,
	0xd6, 0x67, 0x79, 0xf4, 0x10, 0x7d, 0xa4, 0xb2, 0xcd, 0xc7, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff,
	0xf3, 0xe9, 0x85, 0x34, 0x5a, 0x01, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// AppGateClient is the client API for AppGate service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type AppGateClient interface {
	OpenShell(ctx context.Context, opts ...grpc.CallOption) (AppGate_OpenShellClient, error)
}

type appGateClient struct {
	cc *grpc.ClientConn
}

func NewAppGateClient(cc *grpc.ClientConn) AppGateClient {
	return &appGateClient{cc}
}

func (c *appGateClient) OpenShell(ctx context.Context, opts ...grpc.CallOption) (AppGate_OpenShellClient, error) {
	stream, err := c.cc.NewStream(ctx, &_AppGate_serviceDesc.Streams[0], "/rpc.AppGate/OpenShell", opts...)
	if err != nil {
		return nil, err
	}
	x := &appGateOpenShellClient{stream}
	return x, nil
}

type AppGate_OpenShellClient interface {
	Send(*StdIn) error
	Recv() (*StdOut, error)
	grpc.ClientStream
}

type appGateOpenShellClient struct {
	grpc.ClientStream
}

func (x *appGateOpenShellClient) Send(m *StdIn) error {
	return x.ClientStream.SendMsg(m)
}

func (x *appGateOpenShellClient) Recv() (*StdOut, error) {
	m := new(StdOut)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// AppGateServer is the server API for AppGate service.
type AppGateServer interface {
	OpenShell(AppGate_OpenShellServer) error
}

// UnimplementedAppGateServer can be embedded to have forward compatible implementations.
type UnimplementedAppGateServer struct {
}

func (*UnimplementedAppGateServer) OpenShell(srv AppGate_OpenShellServer) error {
	return status.Errorf(codes.Unimplemented, "method OpenShell not implemented")
}

func RegisterAppGateServer(s *grpc.Server, srv AppGateServer) {
	s.RegisterService(&_AppGate_serviceDesc, srv)
}

func _AppGate_OpenShell_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AppGateServer).OpenShell(&appGateOpenShellServer{stream})
}

type AppGate_OpenShellServer interface {
	Send(*StdOut) error
	Recv() (*StdIn, error)
	grpc.ServerStream
}

type appGateOpenShellServer struct {
	grpc.ServerStream
}

func (x *appGateOpenShellServer) Send(m *StdOut) error {
	return x.ServerStream.SendMsg(m)
}

func (x *appGateOpenShellServer) Recv() (*StdIn, error) {
	m := new(StdIn)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _AppGate_serviceDesc = grpc.ServiceDesc{
	ServiceName: "rpc.AppGate",
	HandlerType: (*AppGateServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OpenShell",
			Handler:       _AppGate_OpenShell_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "rpc.proto",
}
